// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef smape_Ed_h
#define smape_Ed_h
#include <FL/Fl.H>
#include <stdio.h>
#include <stdlib.h>
extern int current_threshold; 
void mapcc_cb(Fl_Widget* widget,void* user_data);
void menu_cb(Fl_Widget*,void* user_data);
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *main_menu;
#include <FL/Fl_Group.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *scan_threshold;
#include <FL/Fl_Button.H>
extern Fl_Button *invert_sign;
extern Fl_Menu_Item menu_main_menu[];
#define save_all (menu_main_menu+2)
#endif
